fix Windows paths
ultrabug/mkdocs-static-i18n pull request #11
Opened 2021-03-08 02:17 UTC by cacrespo

not elegant but solves #7 😄

2021-03-09 20:48 UTC, ultrabug commented
Hi @cacrespo thanks for taking on your time to improve the project.

I manipulate `dest_path` in multiple other places like in line 101 but it does not seem to matter for your testing so I'm a bit puzzled about why this `joinpath()` alone is doing some magic :confused: 

I have no Windows to check this on, would you mind showing a real dest_path before / after example?

2021-03-09 23:24 UTC, cacrespo commented
Hi @ultrabug, happy to be of help! 😄 

I think the problem is when the path string finish with "/" (for example in line 95). The line 101 isn't the case.
In facts, I see that there is no need  .joinpath(). Only Path() should work.

Look how works in Windows:
```
>>> from pathlib import Path
>>> a = "C:\Windows/"
>>> b = str(Path(a))

>>> print (a.replace("Windows", "") )
C:\/

>>> print (b.replace("Windows", "") )
C:\
```

This are the folders without the adjust
C:.
├───css
├───en
│   ├───topic1
│   │   └───index.en
│   └───topic2
│       └───index.en
├───fonts
├───fr
│   ├───index.fr
│   ├───topic1
│   │   └───index.fr
│   └───topic2
│       └───index.en
├───img
├───js
├───search
├───topic1
│   └───index.en
└───topic2

And now with de fix:
C:.
├───css
├───en
│   ├───topic1
│   └───topic2
├───fonts
├───fr
│   ├───topic1
│   └───topic2
├───img
├───js
├───search
├───topic1
└───topic2

2021-03-10 14:05 UTC, cacrespo commented
> Dunno if I'm clear enough?

Yes! I will try to do it 👍

2021-03-14 08:22 UTC, ultrabug requested changes
Thanks a lot, we're almost there!

I think the function should take the original i18n_page and just str(Path()) its dest_path and abs_dest_path properties before returning it

That way it will be a very simple and clean change

2021-03-14 08:22 UTC, ultrabug commented on mkdocs_static_i18n/plugin.py
>          return i18n_page
```suggestion
        return self._fix_dest_paths(i18n_page)
```

I guess it's better and safer to fix the object on return please so we're not stuck in a if / else context.

2021-03-14 08:22 UTC, ultrabug commented on mkdocs_static_i18n/plugin.py
> +    def _fix_dest_paths(self, page):
Just take the original `i18n_page` as input

2021-03-14 08:22 UTC, ultrabug commented on mkdocs_static_i18n/plugin.py
> +        i18n_page = deepcopy(page)
Do not make a copy, we just want to modify the referenced object

2021-03-14 08:22 UTC, ultrabug commented on mkdocs_static_i18n/plugin.py
> +        i18n_page.dest_path = page.dest_path.replace(str(Path(f"{page.name}/")), "")
please leave the `replace()` stuff where they are in the code, in this function we only want to Path() them

```suggestion
        i18n_page.dest_path = str(Path(i18n_page.dest_path))
```

2021-03-14 08:22 UTC, ultrabug commented on mkdocs_static_i18n/plugin.py
> +        i18n_page.dest_path = page.dest_path.replace(str(Path(f"{page.name}/")), "")
(same for abs_dest_path)

2021-03-14 22:10 UTC, cacrespo commented
Hi @ultrabug! Thanks for the feedback and sorry if I can't follow you properly. My English is not very good and "my Python" is worse 😝 

I think the `replace()` is still necesary. Look the output of this test I make: 

```
    def _fix_dest_paths(self, page):
        """
        Corrects paths to work fine on Windows and Unix system
        """
        i18n_page = deepcopy(page)

        print(str(Path(i18n_page.dest_path)))
        print(i18n_page.dest_path)

        i18n_page.dest_path = page.dest_path.replace(str(Path(f"{page.name}/")), "")

        print("fix:", i18n_page.dest_path)
        print("fix:", str(Path(i18n_page.dest_path)))
```
This is the output:
```
index.fr\index.html
index.fr\index.html
fix: \index.html
fix: \index.html
topic1\index.en\index.html
topic1\index.en\index.html
fix: topic1\\index.html
fix: topic1\index.html
...
```
Only if I maintain the `replace()` the tree folder structure is built correctly. What do you think?

2021-03-15 12:35 UTC, ultrabug commented
> Thanks for the feedback and sorry if I can't follow you properly

On the contrary, it's me feeling bad to get you changing code

> I think the replace() is still necesary

Yes, that's why I'm saying to leave the replace() as it is today in the current code

I'm only proposing to use the `_fix_dest_paths` to str(Path()) them after

2021-03-15 12:43 UTC, ultrabug commented
If I'm not clear enough, I can put up a PR to show you what I mean

My interest here is to preserve your contribution

2021-03-16 02:31 UTC, cacrespo commented
Hi @ultrabug! I revised all the changes and I think we can't just take the original i18n_page and returning it with the properties adjusted. Let me explain you:
In all `replace()` we search for path with forward slashes and it is the problem in Windows. For example, when in the test case  run:

`i18n_page.dest_path = page.dest_path.replace(f"{page.name}/", "")` 
on Windows the value of `i18n_page.dest_path` is `topic1\index.en\index.html` and we need replace `index.en/` (please look at "/").

This is all in if/else context before return i18n_page so if we want to apply the function fix_path on return line is necessary move all the replace hack to the function.

Another solution I tried is convert all the paths with [.as_posix()](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix) but didn't work (for me). Even if I try only in if/else block. 
So, I think the more simplest and cleanest solution is reconsiderate the commit b374bb0

> My interest here is to preserve your contribution

Thank you very much. You are very considerate.
I think my contribution is already made even if we finally don't merge the pull request. It is OK for me if you create and merge other PR (really I want to know how fix the problem). I can test it.

2021-03-16 02:31 UTC, cacrespo commented
Hi @ultrabug! I revised all the changes and I think we can't just take the original i18n_page and returning it with the properties adjusted. Let me explain you:
In all `replace()` we search for path with forward slashes and it is the problem in Windows. For example, when in the test case  run:

`i18n_page.dest_path = page.dest_path.replace(f"{page.name}/", "")` 
on Windows the value of `i18n_page.dest_path` is `topic1\index.en\index.html` and we need replace `index.en/` (please look at "/").

This is all in if/else context before return i18n_page so if we want to apply the function fix_path on return line is necessary move all the replace hack to the function.

Another solution I tried is convert all the paths with [.as_posix()](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix) but didn't work (for me). Even if I try only in if/else block. 
So, I think the more simplest and cleanest solution is reconsiderate the commit b374bb0

> My interest here is to preserve your contribution

Thank you very much. You are very considerate.
I think my contribution is already made even if we finally don't merge the pull request. It is OK for me if you create and merge other PR (really I want to know how fix the problem). I can test it.

2021-03-16 02:31 UTC, cacrespo commented
Hi @ultrabug! I revised all the changes and I think we can't just take the original i18n_page and returning it with the properties adjusted. Let me explain you:
In all `replace()` we search for path with forward slashes and it is the problem in Windows. For example, when in the test case  run:

`i18n_page.dest_path = page.dest_path.replace(f"{page.name}/", "")` 
on Windows the value of `i18n_page.dest_path` is `topic1\index.en\index.html` and we need replace `index.en/` (please look at "/").

This is all in if/else context before return i18n_page so if we want to apply the function fix_path on return line is necessary move all the replace hack to the function.

Another solution I tried is convert all the paths with [.as_posix()](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix) but didn't work (for me). Even if I try only in if/else block. 
So, I think the more simplest and cleanest solution is reconsiderate the commit b374bb0

> My interest here is to preserve your contribution

Thank you very much. You are very considerate.
I think my contribution is already made even if we finally don't merge the pull request. It is OK for me if you create and merge other PR (really I want to know how fix the problem). I can test it.

2021-03-22 13:40 UTC, ultrabug commented
Hi mate, please see #13

2021-03-23 10:40 UTC, cacrespo commented
Hello @ultrabug!
In a few days I will see this. 😄

2021-04-06 13:11 UTC, ultrabug commented
fixed in #13

2021-04-06 13:11 UTC, closed without merging